name: musl.cc ninja - latest master matrix

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [ninja]
        os_id: [alpine]
        os_version_id: [edge]
        arch:
          [
            arm-linux-musleabihf,
            armv7l-linux-musleabihf,
            aarch64-linux-musl,
            x86_64-linux-musl,
          ]
        include:
          - arch: arm-linux-musleabihf
            binary_name: armhf
            
          - arch: armv7l-linux-musleabihf
            binary_name: armv7
            
          - arch: aarch64-linux-musl
            binary_name: aarch64
            
          - arch: x86_64-linux-musl
            binary_name: x86_64

    name: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap musl cross make toolchains
        run: |
          curl -sLO https://github.com/userdocs/qbt-musl-cross-make/releases/latest/download/${{ matrix.arch }}.tar.gz
          tar xf ${{ matrix.arch }}.tar.gz --strip-components=1 -C "$(pwd)"
          echo "release_asset=${{ matrix.arch }}" >> $GITHUB_ENV

          echo "PATH=/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" > env.custom
          echo "LDFLAGS=-s -static --static" >> env.custom
          echo "CHOST=${{ matrix.arch }}" >> env.custom
          echo "CC=${{ matrix.arch }}-gcc" >> env.custom
          echo "AR=${{ matrix.arch }}-ar" >> env.custom
          echo "CXX=${{ matrix.arch }}-g++" >> env.custom

      - name: Docker multiarch bootstrap
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Create docker multiarch ${{ matrix.docker_arch }} container
        run: docker run --name multiarch -it -d --env-file env.custom -w /root -v ${{ github.workspace }}:/root alpine:edge

      - name: Run apk update
        run: docker exec multiarch apk update --repository="${{ env.CDN }}"

      - name: Run apk upgrade
        run: docker exec multiarch apk upgrade --repository="${{ env.CDN }}"

      - name: Run apk to install the core build dependencies
        run: docker exec multiarch apk add build-base git curl linux-headers cmake re2c

      - name: Create tag env
        run: echo "ninja_github_tag=$(curl -sL "https://raw.githubusercontent.com/ninja-build/ninja/master/src/version.cc" | sed -rn 's|const char\* kNinjaVersion = "(.*)";|\1|p' | sed 's/\.git//g')" >> $GITHUB_ENV

      - name: Host - Git clone ${{ matrix.name }}
        run: git clone --no-tags --single-branch --branch master --depth=1 "https://github.com/ninja-build/ninja.git" "${{ matrix.name }}"

      - name: Configure ${{ matrix.name }}
        run: >
          docker exec -w /root/${{ matrix.name }} multiarch cmake -B build
          -D CMAKE_BUILD_TYPE="release"
          -D CMAKE_CXX_STANDARD="17"
          -D CMAKE_INSTALL_PREFIX="/root"

      - name: Cmake Build ${{ matrix.name }}
        run: docker exec -w /root/${{ matrix.name }} multiarch cmake --build build

      - name: Cmake Install ${{ matrix.name }}
        run: docker exec -w /root/${{ matrix.name }} multiarch cmake --install build

      - name: Rename ${{ matrix.name }} to ${{ env.release_asset }}
        run: docker exec multiarch mv -f /root/bin/${{ matrix.name }} /root/bin/ninja-${{ matrix.binary_name }}

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          artifacts: bin/ninja-${{ matrix.binary_name }}
          replacesArtifacts: true
          tag: ${{ env.ninja_github_tag }}
          name: ${{ matrix.name }} ${{ env.ninja_github_tag }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
