name: mcm ninja build - archive

on:
  workflow_dispatch:
    inputs:
      skip_rerun:
        description: "Skip rerun?"
        required: true
        default: false
        type: boolean
      retries:
        description: "Number of rerun retries"
        required: true
        default: "2"
        type: choice
        options: ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

concurrency:
  group: mcm-ninja-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04 # needs to be ubuntu-24.04 for qemu-user-static loongarch64 support
    name: ${{ matrix.arch }}
    permissions:
      contents: write
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        name: [ninja]
        os_id: [alpine]
        os_version_id: [edge]
        include:
          - arch: aarch64-linux-musl
            binary_name: aarch64
          - arch: arm-linux-musleabi
            binary_name: armv5
          - arch: arm-linux-musleabihf
            binary_name: armhf
          - arch: armv6-linux-musleabihf
            binary_name: armv6
          - arch: armv7l-linux-musleabihf
            binary_name: armv7
          - arch: i686-linux-musl
            binary_name: x86
          - arch: x86_64-linux-musl
            binary_name: x86_64
          - arch: mips-linux-musl
            binary_name: mips
          - arch: mips64-linux-musl
            binary_name: mips64
          - arch: mips64el-linux-musl
            binary_name: mips64el
          - arch: mipsel-linux-musl
            binary_name: mipsel
          - arch: powerpc-linux-musl
            binary_name: powerpc
          - arch: powerpc64le-linux-musl
            binary_name: powerpc64le
          - arch: s390x-linux-musl
            binary_name: s390x
          - arch: riscv64-linux-musl
            binary_name: riscv64
          - arch: loongarch64-linux-musl
            binary_name: loongarch64

    steps:
      - name: Host - checkout
        uses: actions/checkout@v4

      - name: Bootstrap musl cross make toolchains
        run: |
          curl -sLO https://github.com/userdocs/qbt-musl-cross-make/releases/latest/download/${{ matrix.arch }}.tar.xz
          tar xf ${{ matrix.arch }}.tar.xz --strip-components=1 -C "$(pwd)"
          echo "release_asset=${{ matrix.arch }}" >> $GITHUB_ENV

          echo "PATH=/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" > env.custom
          echo "LDFLAGS=-s -static --static" >> env.custom
          echo "CHOST=${{ matrix.arch }}" >> env.custom
          echo "CC=${{ matrix.arch }}-gcc" >> env.custom
          echo "AR=${{ matrix.arch }}-ar" >> env.custom
          echo "CXX=${{ matrix.arch }}-g++" >> env.custom

      - name: Docker multiarch bootstrap
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Create docker multiarch ${{ matrix.docker_arch }} container
        run: docker run --name multiarch -it -d --env-file env.custom -w /root -v ${{ github.workspace }}:/root alpine:edge

      - name: Run apk update
        run: docker exec multiarch apk update --repository="${{ env.CDN }}"

      - name: Run apk upgrade
        run: docker exec multiarch apk upgrade --repository="${{ env.CDN }}"

      - name: Run apk to install the core build dependencies
        run: docker exec multiarch apk add build-base git curl linux-headers cmake re2c python3 gtest

      - name: Create tag env
        run: echo "ninja_github_tag=$(curl -sL "https://raw.githubusercontent.com/ninja-build/ninja/master/src/version.cc" | sed -rn 's|const char\* kNinjaVersion = "(.*)";|\1|p' | sed 's/\.git//g')" >> $GITHUB_ENV

      - name: Host - Git clone ${{ matrix.name }}
        run: git clone --no-tags --single-branch --branch master --depth=1 "https://github.com/ninja-build/ninja.git" "${{ matrix.name }}"

      - name: Configure ${{ matrix.name }}
        run: >
          docker exec -w /root/${{ matrix.name }} multiarch cmake -B build
          -D CMAKE_BUILD_TYPE="release"
          -D CMAKE_CXX_STANDARD="20"
          -D CMAKE_INSTALL_PREFIX="/root"
          -D BUILD_TESTING=off

      - name: Cmake Build ${{ matrix.name }}
        run: docker exec -w /root/${{ matrix.name }} multiarch cmake --build build --parallel --config Release

      - name: Cmake Install ${{ matrix.name }}
        run: docker exec -w /root/${{ matrix.name }} multiarch cmake --install build

      - name: Rename ${{ matrix.name }} to ${{ env.release_asset }}
        run: docker exec multiarch mv -f /root/bin/${{ matrix.name }} /root/ninja-${{ matrix.binary_name }}

      - name: Host - signed build provenance attestations
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ninja-${{ matrix.binary_name }}

      - name: Upload artifact - ${{ matrix.binary_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ninja-${{ matrix.binary_name }}
          path: ninja-${{ matrix.binary_name }}

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          artifacts: ninja-${{ matrix.binary_name }}
          replacesArtifacts: true
          tag: v${{ env.ninja_github_tag }}
          name: ${{ matrix.name }} ${{ env.ninja_github_tag }}
          allowUpdates: true
          token: ${{ github.token }}

  ci-auto-rerun-failed-jobs:
    if: failure() && (github.event.inputs.skip_rerun || 'false') == 'false'
    needs: [build]
    concurrency:
      group: ci-auto-rerun-failed-jobs
      cancel-in-progress: true
    permissions:
      actions: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: "${{ secrets.AUTO_RERUN || github.token }}"
      github_repo: "" # To use ci-auto-rerun-failed-jobs.yml hosted in a remote repository else default to the current repository. Requires PAT token AUTO_RERUN
    steps:
      - uses: actions/checkout@v4
      - name: ci-auto-rerun-failed-jobs via ${{ env.github_repo || github.repository }}
        run: >
          gh workflow run ci-auto-rerun-failed-jobs.yml
          --repo "${{ env.github_repo || github.repository }}"
          -f github_repo=${{ github.repository }}
          -f run_id=${{ github.run_id }}
          -f attempts=${{ github.run_attempt }}
          -f retries=${{ github.event.inputs.retries || '1' }}
          -f distinct_id=${{ github.event.inputs.distinct_id }}
