name: mcm ninja build

on:
  workflow_dispatch:
    inputs:
      skip_rerun:
        description: "Skip rerun?"
        required: true
        default: false
        type: boolean
      retries:
        description: "Number of rerun retries"
        required: true
        default: "2"
        type: choice
        options: ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

  schedule:
    - cron: "0 */23 * * *"

concurrency:
  group: mcm-ninja-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-arm # needs to be ubuntu-24.04 for qemu-user-static loongarch64 support
    name: ${{ matrix.arch_type }}
    permissions:
      contents: write
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        name: [ninja]
        os_id: [alpine]
        os_version_id: [edge]
        arch_type:
          [
            "aarch64-linux-musl",
            "arm-linux-musleabi",
            "arm-linux-musleabihf",
            "armv6-linux-musleabihf",
            "armv7l-linux-musleabihf",
            "i686-linux-musl",
            "x86_64-linux-musl",
            "mips-linux-musl",
            "mipsel-linux-musl",
            "mips64-linux-musl",
            "mips64el-linux-musl",
            "powerpc-linux-musl",
            "powerpc64le-linux-musl",
            "s390x-linux-musl",
            "riscv64-linux-musl",
            "loongarch64-linux-musl",
          ]
        include:
          - arch_type: "aarch64-linux-musl"
            binary_name: aarch64
          - arch_type: "arm-linux-musleabi"
            binary_name: armv5
          - arch_type: "arm-linux-musleabihf"
            binary_name: armhf
          - arch_type: "armv6-linux-musleabihf"
            binary_name: armv6
          - arch_type: "armv7l-linux-musleabihf"
            binary_name: armv7
          - arch_type: "i686-linux-musl"
            binary_name: x86
          - arch_type: "x86_64-linux-musl"
            binary_name: x86_64
          - arch_type: "mips-linux-musl"
            binary_name: mips
          - arch_type: "mips64-linux-musl"
            binary_name: mips64
          - arch_type: "mips64el-linux-musl"
            binary_name: mips64el
          - arch_type: "mipsel-linux-musl"
            binary_name: mipsel
          - arch_type: "powerpc-linux-musl"
            binary_name: powerpc
          - arch_type: "powerpc64le-linux-musl"
            binary_name: powerpc64le
          - arch_type: "s390x-linux-musl"
            binary_name: s390x
          - arch_type: "riscv64-linux-musl"
            binary_name: riscv64
          - arch_type: "loongarch64-linux-musl"
            binary_name: loongarch64

    env:
      container_name: crossbuild

    steps:
      - name: Host - checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create docker ${{ env.container_name }} ${{ matrix.docker_arch }} container
        run: |
          env > env.custom
          printf 'LDFLAGS="-s -static --static"' >> env.custom
          docker run --name ${container_name} -it -d --env-file env.custom -w /home/github -v ${{ github.workspace }}:/home/github ghcr.io/userdocs/qbt-musl-cross-make:${{ matrix.arch_type }}

      - name: env test
        run: docker exec ${container_name} sh -c 'env'

      - name: Create tag env
        run: echo "ninja_github_tag=$(curl -sL "https://raw.githubusercontent.com/ninja-build/ninja/master/src/version.cc" | sed -rn 's|const char\* kNinjaVersion = "(.*)";|\1|p' | sed 's/\.git//g')" >> $GITHUB_ENV

      - name: Host - Git clone ${{ matrix.name }}
        run: git clone --no-tags --single-branch --branch master --depth=1 "https://github.com/ninja-build/ninja.git" "${{ matrix.name }}"

      - name: Configure ${{ matrix.name }}
        run: >
          docker exec -w /home/github/${{ matrix.name }} ${container_name} cmake -B build
          -D CMAKE_BUILD_TYPE="release"
          -D CMAKE_CXX_STANDARD="20"
          -D CMAKE_INSTALL_PREFIX="/home/github"
          -D BUILD_TESTING=off

      - name: Cmake Build ${{ matrix.name }}
        run: docker exec -w /home/github/${{ matrix.name }} ${container_name} cmake --build build --parallel --config Release

      - name: Cmake Install ${{ matrix.name }}
        run: docker exec -w /home/github/${{ matrix.name }} ${container_name} cmake --install build

      - name: Rename ${{ matrix.name }} to ${{ env.release_asset }}
        run: docker exec ${container_name} mv -f /home/github/bin/${{ matrix.name }} /home/github/ninja-${{ matrix.binary_name }}

      - name: Host - signed build provenance attestations
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ninja-${{ matrix.binary_name }}

      - name: Upload artifact - ${{ matrix.binary_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ninja-${{ matrix.binary_name }}
          path: ninja-${{ matrix.binary_name }}

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          artifacts: ninja-${{ matrix.binary_name }}
          replacesArtifacts: true
          tag: v${{ env.ninja_github_tag }}
          name: ${{ matrix.name }} ${{ env.ninja_github_tag }}
          allowUpdates: true
          token: ${{ github.token }}

  ci-auto-rerun-failed-jobs:
    if: failure() && (github.event.inputs.skip_rerun || 'false') == 'false'
    needs: [build]
    concurrency:
      group: ci-auto-rerun-failed-jobs
      cancel-in-progress: true
    permissions:
      actions: write
    runs-on: ubuntu-24.04-arm
    env:
      GH_TOKEN: "${{ secrets.AUTO_RERUN || github.token }}"
      github_repo: "" # To use ci-auto-rerun-failed-jobs.yml hosted in a remote repository else default to the current repository. Requires PAT token AUTO_RERUN
      retries: ${{ github.event.inputs.retries || '1' }}
      distinct_id: ${{ github.event.inputs.distinct_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: ci-auto-rerun-failed-jobs via ${{ env.github_repo || github.repository }}
        run: >
          gh workflow run ci-auto-rerun-failed-jobs-action.yml
          --repo "${github_repo:-$GITHUB_REPOSITORY}"
          -f github_repo=${GITHUB_REPOSITORY}
          -f run_id=${GITHUB_RUN_ID}
          -f attempts=${GITHUB_RUN_ATTEMPT}
          -f retries=${retries}
          -f distinct_id=${distinct_id}
